site_name: figpptx Documentation
theme: material
nav:
    - Home: 'index.md'
    - Tutorial: 
        - "Introduction": 'tutorial/index.md'
        - "Basic Usage": 'tutorial/basic.md'
repo_name: "https://github.com/Sillte/figpptx"
markdown_extensions:
    - admonition
    - codehilite
